=== Einzelganger/templates/xml/dtd/offerte.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xi="http://www.w3.org/2001/XInclude"
    xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" vc:minVersion="1.0" vc:maxVersion="1.1">
  <xs:import namespace="http://www.w3.org/XML/1998/namespace" schemaLocation="http://www.w3.org/2001/xml.xsd" />
  <xs:import namespace="http://www.w3.org/2001/XInclude" schemaLocation="http://www.w3.org/2001/XInclude/XInclude.xsd"/>
  <xs:element name="offerte">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="meta"/>
        <xs:element maxOccurs="unbounded" ref="section"/>
        <xs:element maxOccurs="unbounded" minOccurs="0" ref="annex"/>
        <xs:element maxOccurs="unbounded" minOccurs="1" ref="generate_waivers"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="meta">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="offered_service_long"/>
        <xs:element ref="offered_service_short"/>
        <xs:element ref="ros"/>
        <xs:element ref="targets"/>
        <xs:element ref="permission_parties"/>
        <xs:element ref="pentestinfo"/>
        <xs:element ref="version_history"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="offered_service_long" type="xs:string"/>
  <xs:element name="offered_service_short" type="xs:string"/>
  <xs:element name="full_name" type="xs:string"/>
  <xs:element name="short_name" type="xs:string"/>
  <xs:element name="city" type="xs:string"/>
  <xs:element name="country" type="xs:string"/>
  <xs:element name="coc">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:integer">
          <xs:attribute name="nationality" type="xs:string" />
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="legal_rep" type="xs:string"/>
  <xs:element name="waiver_rep" type="xs:string"/>
  <xs:element name="ros">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="full_name"/>
        <xs:element ref="short_name"/>
        <xs:element ref="legal_rep"/>
        <xs:element ref="poc1"/>
        <xs:element ref="address"/>
        <xs:element ref="postal_code"/>
        <xs:element ref="city"/>
        <xs:element ref="country"/>
        <xs:element ref="email"/>
      </xs:sequence>
      <xs:attribute ref="xml:base"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="poc1" type="xs:string"/>
  <xs:element name="postal_code" type="xs:string"/>
  <xs:element name="targets">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="target"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="target" type="xs:string"/>
  <xs:element name="permission_parties">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="1" ref="client"/>
        <xs:element maxOccurs="unbounded" minOccurs="0" ref="party"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="party">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="full_name"/>
        <xs:element ref="short_name"/>
        <xs:element ref="waiver_rep"/>
        <xs:element ref="address"/>
        <xs:element ref="city"/>
        <xs:element ref="country"/>
        <xs:element minOccurs="0" ref="coc"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="client">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="full_name"/>
        <xs:element ref="short_name"/>
        <xs:element ref="legal_rep"/>
        <xs:element ref="waiver_rep"/>
        <xs:element ref="poc1"/>
        <xs:element ref="address"/>
        <xs:element ref="city"/>
        <xs:element ref="country"/>
        <xs:element minOccurs="0" ref="coc"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="pentestinfo">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="duration"/>
        <xs:element ref="test_planning"/>
        <xs:element ref="report_writing"/>
        <xs:element ref="report_due"/>
        <xs:element ref="nature"/>
        <xs:element ref="type"/>
        <xs:element ref="fee"/>
        <xs:element minOccurs="0" ref="target_application"/>
        <xs:element minOccurs="0" ref="target_application_producer"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="duration" type="xs:nonNegativeInteger"/>
  <xs:element name="test_planning" type="xs:string"/>
  <xs:element name="report_writing" type="xs:string"/>
  <xs:element name="report_due" type="xs:string"/>
  <xs:element name="nature" type="xs:string"/>
  <xs:element name="type">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="black-box"/>
            <xs:enumeration value="crystal-box"/>
            <xs:enumeration value="grey-box"/>
          </xs:restriction>
        </xs:simpleType>
  </xs:element>
  <xs:element name="fee" type="xs:string"/>
  <xs:element name="target_application" type="xs:string"/>
  <xs:element name="target_application_producer" type="xs:string"/>
  <xs:element name="version_history">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="version"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="version">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="v_author" maxOccurs="unbounded"/>
        <xs:element ref="v_description"/>
      </xs:sequence>
      <xs:attribute name="date" use="required" type="xs:dateTime"/>
      <xs:attribute name="number" use="required" type="xs:NMTOKEN"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="contact">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="name"/>
        <xs:element ref="address"/>
        <xs:element ref="email"/>
      </xs:sequence>
      <xs:attribute ref="xml:base"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="address">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="br"/>
        <xs:group ref="placeholders"></xs:group>
      </xs:choice>
    </xs:complexType>
  </xs:element>
  <xs:element name="phone" type="xs:string"/>
  <xs:element name="email" type="xs:string"/>
  <xs:element name="generate_targets">
    <xs:complexType/>
  </xs:element>
  <xs:element name="annex">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="title"/>
        <xs:choice maxOccurs="unbounded">
          <xs:element name="p" type="block"/>
          <xs:element ref="pre"/>
          <xs:element ref="code"/>
          <xs:element ref="table"/>
          <xs:element ref="ol"/>
          <xs:element ref="ul"/>
          <xs:element ref="img"/>
          <xs:element ref="section"/>
          <xs:element ref="generate_targets"/>
        </xs:choice>
      </xs:sequence>
      <xs:attribute ref="xml:base"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="generate_waivers"/>
  <xs:element name="title">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="br"/>
        <xs:group ref="placeholders"/>
      </xs:choice>
    </xs:complexType>
  </xs:element>
  <xs:element name="v_author" type="xs:string"/>
  <xs:element name="v_description" type="xs:string"/>
  <xs:element name="name">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:group ref="placeholders"></xs:group>
      </xs:choice>
    </xs:complexType>
  </xs:element>
  <xs:element name="br">
    <xs:complexType/>
  </xs:element>
  <xs:element name="section">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="title"/>
        <xs:choice minOccurs="0" maxOccurs="unbounded">
          <xs:element ref="pre"/>
          <xs:element ref="code"/>
          <xs:element name="p" type="block"/>
          <xs:element ref="section"/>
          <xs:element ref="table"/>
          <xs:element ref="ul"/>
          <xs:element ref="ol"/>
          <xs:element ref="img"/>
          <xs:element ref="generate_targets"/>
          <xs:element ref="contact"/>
          <xs:element ref="generate_offer_signature_box"/>
        </xs:choice>
      </xs:sequence>
      <xs:attribute name="break" use="optional">
        <xs:simpleType> 
          <xs:restriction base="xs:string"> 
            <xs:enumeration value="before"/>
            <xs:enumeration value="after"/>
          </xs:restriction> 
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute ref="xml:base"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="table">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="tr"/>
      </xs:sequence>
      <xs:attribute name="border" use="optional" type="xs:integer"/>
      <xs:attribute name="cols" use="optional" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="tr">
    <xs:complexType>
      <xs:choice maxOccurs="unbounded" minOccurs="1">
        <xs:element ref="td"/>
        <xs:element ref="th"/>
      </xs:choice>
    </xs:complexType>
  </xs:element>
  <xs:element name="td">
    <xs:complexType mixed="true">
      <xs:choice maxOccurs="unbounded">
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="a"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="b"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="br"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="i"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="u"/>
        <xs:group ref="placeholders"/>
      </xs:choice>
    </xs:complexType>
  </xs:element>
  <xs:element name="th" type="xs:string"/>
  <xs:element name="ul">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" name="li" type="li"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="ol">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" name="li" type="li"/>
      </xs:sequence>
      <xs:attribute name="type" use="optional">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="a"/>
            <xs:enumeration value="A"/>
            <xs:enumeration value="i"/>
            <xs:enumeration value="I"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>
  <xs:complexType name="block" mixed="true">
    <xs:choice maxOccurs="unbounded">
      <xs:element minOccurs="0" maxOccurs="unbounded" ref="a"/>
      <xs:element minOccurs="0" maxOccurs="unbounded" ref="b"/>
      <xs:element minOccurs="0" maxOccurs="unbounded" ref="br"/>
      <xs:element minOccurs="0" maxOccurs="unbounded" ref="i"/>
      <xs:element minOccurs="0" maxOccurs="unbounded" ref="u"/>
      <xs:element minOccurs="0" maxOccurs="unbounded" ref="generate_permission_parties"/>
      <xs:group ref="placeholders"/>
    </xs:choice>
    <xs:attribute ref="xml:base"/>
  </xs:complexType>
  <xs:complexType name="li" mixed="true">
    <xs:choice maxOccurs="unbounded">
      <xs:element minOccurs="0" maxOccurs="unbounded" ref="a"/>
      <xs:element minOccurs="0" maxOccurs="unbounded" ref="b"/>
      <xs:element minOccurs="0" maxOccurs="unbounded" ref="br"/>
      <xs:element minOccurs="0" maxOccurs="unbounded" ref="i"/>
      <xs:element minOccurs="0" maxOccurs="unbounded" ref="u"/>
      <xs:element minOccurs="0" maxOccurs="unbounded" ref="ul"/>
      <xs:element minOccurs="0" maxOccurs="unbounded" ref="ol"/>
        <xs:group ref="placeholders"/>
    </xs:choice>
  </xs:complexType>
  <xs:element name="generate_offer_signature_box"/>
  <xs:element name="generate_permission_parties"/>
  <xs:element name="img">
    <xs:complexType>
      <xs:attribute name="height" use="optional" type="xs:integer"/>
      <xs:attribute name="width" use="optional" type="xs:integer"/>
      <xs:attribute name="src" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="pre">
    <xs:complexType mixed="true">
      <xs:choice>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="a"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="b"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="br"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="i"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="u"/>
        <xs:group ref="placeholders"/>
      </xs:choice>
    </xs:complexType>
  </xs:element>
  <xs:element name="code">
    <xs:complexType mixed="true">
      <xs:choice>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="a"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="b"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="br"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="i"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="u"/>
        <xs:group ref="placeholders"/>
      </xs:choice>
    </xs:complexType>
  </xs:element>
  <xs:element name="a">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute name="href" use="required" type="xs:anyURI"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="b">
    <xs:complexType mixed="true">
      <xs:choice maxOccurs="unbounded">
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="a"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="br"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="i"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="u"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="monospace"/>
        <xs:group ref="placeholders"/>
      </xs:choice>
    </xs:complexType>
  </xs:element>
  <xs:element name="i">
    <xs:complexType mixed="true">
      <xs:choice maxOccurs="unbounded">
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="a"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="b"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="br"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="u"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="monospace"/>
        <xs:group ref="placeholders"/>
      </xs:choice>
    </xs:complexType>
  </xs:element>
  <xs:element name="u">
    <xs:complexType mixed="true">
      <xs:choice maxOccurs="unbounded">
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="a"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="b"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="br"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="i"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="monospace"/>
        <xs:group ref="placeholders"/>
      </xs:choice>
    </xs:complexType>
  </xs:element>
  <xs:element name="monospace">
    <xs:complexType mixed="true">
      <xs:choice maxOccurs="unbounded">
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="a"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="b"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="br"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="i"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="u"/>
        <xs:group ref="placeholders"/>
      </xs:choice>
    </xs:complexType>
  </xs:element>
  
  <!-- Placeholders -->
  <xs:group name="placeholders">
    <xs:choice>
      <xs:element name="c_long"/>
      <xs:element name="c_short"/>
      <xs:element name="c_street"/>
      <xs:element name="c_city"/>
      <xs:element name="c_country"/>
      <xs:element name="c_coc"/>
      <xs:element name="c_legal_rep"/>
      <xs:element name="c_waiver_rep"/>
      <xs:element name="c_poc1"/>
      <xs:element name="ros_long"/>
      <xs:element name="ros_short"/>
      <xs:element name="ros_svc_long"/>
      <xs:element name="ros_svc_short"/>
      <xs:element name="ros_legal_rep"/>
      <xs:element name="ros_poc1"/>
      <xs:element name="t_app"/>
      <xs:element name="t_app_producer"/>
      <xs:element name="p_duration"/>
      <xs:element name="p_boxtype"/>
      <xs:element name="p_fee"/>
      <xs:element name="p_testingduration"/>
      <xs:element name="p_reportwritingduration"/>
      <xs:element name="p_reportdue"/>
    </xs:choice>
</xs:group>
</xs:schema>

=== Einzelganger/templates/xml/doc/examples/exampleofferte.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE offerte []>
<offerte xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../dtd/offerte.xsd" xmlns:xi="http://www.w3.org/2001/XInclude">
    
    <!-- document meta information; to be filled in by the offerte writer  -->
    <meta>
        <offered_service_long>penetration testing services</offered_service_long>
        <offered_service_short>penetration test</offered_service_short>
        <xi:include href="snippets/ros_info.xml"/>
        <targets> <!-- one target element per target -->
            <target>fishinabarrel.sittingduck.com</target>
        </targets>
        <permission_parties>
            <client><!-- mandatory; please add client information -->
                <full_name>Sitting Duck BV</full_name><!-- long client name, e.g. Sitting Duck B.V. -->
                <short_name>Sitting Duck</short_name> <!-- short client name, e.g. Sitting Duck; if no short name: same as long name -->
                <legal_rep>I.M. Portant</legal_rep><!-- customer legal representative (to sign offer) -->
                <waiver_rep>B.I.G. Wig</waiver_rep><!-- customer legal representative (to sign waiver; can be same person as legal_rep) -->
                <poc1>Sir Knowsalot</poc1><!-- first point of contact for customer (during pentest); can be same person as above -->
                <address>Reed Street 42</address>
                <city>Pond City</city> 
                <country>Amazonia</country>
                <coc nationality="Dutch">9999999</coc><!-- chamber of commerce number; if no chamber of commerce number, please delete the whole element -->
            </client>
            <party><!-- optional; if no other party needs to give permission, please remove whole party element -->
                <full_name>h4ck'R'Us</full_name>
                <short_name>h4ck'R'Us</short_name> <!-- short party name; if no short name: same as long name -->
                <waiver_rep>Evil Hacker</waiver_rep> 
                <address>Cave 99</address>
                <city>Darkest Dungeon</city> 
                <country>Underworld</country>
            </party>
        </permission_parties>
        <pentestinfo>
            <duration>10</duration><!-- duration of pentest, in working days -->
            <test_planning>January 1st until January 12th, 2015</test_planning> <!-- date or date range in text, e.g. May 18th until May 25th, 2015 -->
            <report_writing>January 15th until January 20th, 2015</report_writing> <!-- date or date range in text, e.g. May 18th until May 25th, 2015 -->
            <report_due>January 23rd, 2015</report_due> <!-- date or date range in text, e.g. May 18th until May 25th, 2015 -->
            <type>black-box</type><!-- please choose one of the following: black-box, grey-box, crystal-box -->
            <fee>50000</fee><!-- euro is added automatically in the document -->
            <target_application>FishInABarrel</target_application><!-- name of application to be tested (if any; if none, delete target_application element) -->
        </pentestinfo>
        <version_history><!-- needed for date on frontpage and in signature boxes; it is possible to add a new <version> after each review; in that case, make sure to update the date/time -->
            <version date="2015-01-01T10:00:00" number="auto"> <!-- actual date-time here; you can leave the number attribute alone -->
                <v_author>Patricia Piolon</v_author> <!-- name of the author here; for internal use only -->
                <v_description>Initial draft</v_description><!-- for internal use only -->
            </version>
        </version_history>
    </meta>
    <section>
    <title>test</title>
    <section>
        <title>test1</title>
        <p>parabla</p>
    </section>
    <section>
        <title>test1</title>
        <p>parabla</p>
    </section>
</section>
    <section>
        <title>Introduction</title>
        <p><c_long/> (hereafter “<b><c_short/></b>”), with its registered office at <c_street/>, <c_city/>, <c_country/>, has requested <ros_long/> (hereafter “<b><ros_short/></b>”) to perform <ros_svc_long/>. Motivation for this request is that <c_short/> wishes to get a better insight in the IT security of the web application <t_app/> produced by <t_app_producer/>.
</p>
<p>ROS will perform a <ros_svc_short/> by running the app and peering at the screen in great concentration.</p>
<xi:include href="snippets/offerte/setoutscope.xml"/>
</section>
    <section><!-- section with some more info on the application (if any) -->
        <title>The <t_app/> Application</title>
        <p><t_app/> is an application that does things. Nobody is sure what exactly.</p>
        <p>It is written in a mix of Java and C and is prohibited in over 200 countries.</p>
    </section>
<!-- Project overview section (complete section is in a snippet) -->
<xi:include href="snippets/offerte/projectoverview.xml"/>
    <section>
        <title>Pentest Scope</title>
        <p>ROS will focus on the web application and the systems that are accessible using the Internet (backend API). A test environment has been set up to use for the pentest on the web application. Given the complexity of the application, ROS will pay specific attention to important things. ROS will review the source code during the <ros_svc_short/>. The mobile applications (iPhone, Android, Windows) are outside the scope of this pentest.</p>
    </section>
    
    <!-- Prerequisites section (complete section is in a snippet) -->
    <xi:include href="snippets/offerte/prerequisites.xml"/>
    
    <!-- Disclaimer section (complete section is in a snippet) -->
    <xi:include href="snippets/offerte/disclaimer.xml"/>
    
    <!-- Pentest Methodology section (complete section is in a snippet) -->
    <xi:include href="snippets/offerte/pentestmethodology.xml"/>
    <xi:include href="snippets/offerte/codeauditmethodology.xml"/><!-- DELETE IF NOT APPLICABLE -->
    
    <!-- Team and Reporting section (complete section is in a snippet) -->
    <xi:include href="snippets/offerte/teamandreporting.xml"/>


<!-- Planning and payment section (complete section is in a snippet) -->
<xi:include href="snippets/offerte/planningandpayment.xml"/> 
    <!-- About ROS section (complete section is in a snippet) -->
<xi:include href="snippets/offerte/aboutros.xml"/>
    
<!-- Work condition section (complete section is in a snippet) -->
<xi:include href="snippets/offerte/conditions.xml"/>
<!-- General terms and conditions section (complete section is in a snippet) -->
<xi:include href="snippets/offerte/generaltermsandconditions.xml"/>


    <!-- Waivers -->
<generate_waivers/>

    
</offerte>

=== Einzelganger/templates/xml/source/offerte.xml
<?xml version="1.0" encoding="UTF-8"?><offerte xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xi="http://www.w3.org/2001/XInclude" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:fo="http://www.w3.org/1999/XSL/Format" xsi:noNamespaceSchemaLocation="../dtd/offerte.xsd"><!--document meta information; to be filled in by the offerte writer--><meta><offered_service_long>penetration testing services</offered_service_long><!--if there is a shorter way of saying the same thing, you can type it here (it makes for more dynamic offerte text). If not, just repeat the long name.--><offered_service_short>penetration test</offered_service_short><xi:include href="snippets/ros_info.xml"/><targets><!--one target element per target--><target>fishinabarrel.sittingduck.nl</target><target>intothegreatwideopen.sittingduck.nl</target><target>iSoftware(tm)</target></targets><permission_parties><client><!--mandatory; please add client information--><full_name>Sitting Duck B.V.</full_name><!--long client name, e.g. Sitting Duck B.V.--><short_name>Sitting Duck</short_name><!--short client name, e.g. Sitting Duck; if no short name: same as long name--><legal_rep>I.M. Portant</legal_rep><!--customer legal representative (to sign offer)--><waiver_rep>B.I.G. Wig</waiver_rep><!--customer legal representative (to sign waiver; can be same person as legal_rep)--><poc1>Sir Knowsalot</poc1><!--first point of contact for customer (during pentest); can be same person as above--><address>Reed Street 42</address><city>Pond City</city><country>Amazonia</country><coc nationality="Dutch">99999999</coc><!--chamber of commerce number; if no chamber of commerce number, please delete the whole element--></client><party><full_name>Programmers 'R' Us Inc.</full_name><short_name>PRU Inc.</short_name><!--short party name; if no short name: same as long name--><waiver_rep>P. Rogram</waiver_rep><address>Cave 99</address><city>Darkest Dungeon</city><country>Underworld</country></party></permission_parties><pentestinfo><duration>5</duration><!--duration of pentest, in working days--><test_planning>beginning of January 2015</test_planning><!--date or date range in text, e.g. May 18th until May 25th, 2015--><report_writing>???</report_writing><!--date or date range in text, e.g. May 18th until May 25th, 2015--><report_due>January 20th, 2015</report_due><!--date or date range in text, e.g. May 18th until May 25th, 2015--><nature>time-boxed</nature><type>grey-box</type><!--please choose one of the following: black-box, grey-box, crystal-box--><fee>200000</fee><!--euro is added automatically in the document--><target_application>FishInABarrel</target_application><!--name of application/serice to be tested (if any; if none, delete target_application element)--></pentestinfo><version_history><!--needed for date on frontpage and in signature boxes; it is possible to add a new <version> after each review; in that case, make sure to update the date/time--><version number="auto" date="2015-01-01T10:00:00"><!--actual date-time here; you can leave the number attribute alone--><v_author>ROS Writer</v_author><!--name of the author here; for internal use only--><v_description>Initial
                        draft</v_description><!--for internal use only--></version></version_history></meta><section><title>Introduction</title><p><c_long/> (hereafter “<b><c_short/></b>”), with its registered office at
                    <c_street/>, <c_city/>, <c_country/>, has requested <ros_long/> (hereafter
                        “<b><ros_short/></b>”) to perform <ros_svc_long/> on the following targets.</p><xi:include href="snippets/offerte/setoutscope.xml"/></section><!--Project overview section (complete section is in a snippet)--><xi:include href="snippets/offerte/projectoverview.xml"/><!--Prerequisites section (complete section is in a snippet)--><xi:include href="snippets/offerte/prerequisites.xml"/><!--Disclaimer section (complete section is in a snippet)--><xi:include href="snippets/offerte/disclaimer.xml"/><!--Pentest Methodology section--><xi:include href="snippets/offerte/pentestmethodology.xml"/><xi:include href="snippets/offerte/codeauditmethodology.xml"/><xi:include href="snippets/offerte/teamandreporting.xml"/><!--Planning and payment section (complete section is in a snippet)--><xi:include href="snippets/offerte/planningandpayment.xml"/><!--About ROS section (complete section is in a snippet)--><xi:include href="snippets/offerte/aboutros.xml"/><!--Work condition section (complete section is in a snippet)--><xi:include href="snippets/offerte/conditions.xml"/><!--General terms and conditions section (complete section is in a snippet)--><xi:include href="snippets/offerte/generaltermsandconditions.xml"/><!--Waivers--><generate_waivers/></offerte>
